### ISSUE TITLE
How do I test singal ECG signal in  CSV file format after generating the model?

### ISSUE THREAD

**Issue by karimkhanp** [CVxTz/ECG_Heartbeat_Classification#2]
I installed required dependencies and run the code.

But I could not figure out how to test singal csv signal I have.

**Comment by CVxTz** [comment]
Sorry to hear that.
What do you expect by opening this issue ?

**Comment by karimkhanp** [comment]
I have a patient's ECG signal in CSV form. I want to test it using your model. So wanted to know how can I test it. 
I have generated the model using your code but not sure how to test it on my data(csv file)

**Comment by CVxTz** [comment]
I understand that.
I don't know how your csv looks like, so I would not be able to help you.
In this repo I worked with pre-processed individual heartbeats, I don't
know how the pre-processing was performed.
Best,

**Comment by karimkhanp** [comment]
okay, Thanks for your reply @CVxTz
